### PR TITLE
Update hebrew  file

### PR DESCRIPTION
**Pull request by ShlomoCode**
It is a bit uncertain if it is really correct to translate "topic name" literally, but I had no other idea.

### CODE REVIEW

**Comment by ShlomoCode** [comment]
cc @julianlam 😉

**Comment by julianlam** [comment]
:smile: "topic name" can be localised to anything that is descriptive in your language. I think "topic name" is what the creator of ntfy uses, but you could really call it anything.

**Comment by julianlam** [comment]
Here the creator just uses "topic" https://github.com/binwiederhier/ntfy/blob/main/web/public/static/langs/en.json

**Comment by ShlomoCode** [comment]
Maybe "device ID"?

**Comment by ShlomoCode** [comment]
@julianlam Ready to merge

**Comment by julianlam** [comment]
It is your localisation, so it is up to you 😊

**Comment by julianlam** [comment]
Am afk but will merge next

**Pull request merged**
